### PR TITLE
handle the power transition for SGX_ERROR_ENCLAVE_LOST

### PR DESCRIPTION
**Pull request by z1queue**
## Description
Fix the ecall_ipc_entry_point, app sgx_error::SGX_ERROR_ENCLAVE_LOST #175 

Fixes # (issue)

## Type of change (select applied and DELETE the others)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API change with a documentation update
- [ ] Additional test coverage
- [ ] Code cleanup or just sync with upstream third-party crates

## Checklist (check ALL before submitting PR, even not applicable)

- [x] Fork the repo and create your branch from `master`.
- [x] If you've added code that should be tested, add tests.
- [x] If you've changed APIs, update the documentation.
- [x] Ensure the tests pass (see CI results).
- [x] Make sure your code lints/format.

### CODE REVIEW

**Comment by mssun** [comment]
Thank you for the PR. We will review it as soon as possible. BTW, how did you test this issue?

I found that the sample code said:

```
        << "Please take the following actions:" << endl
        << "    1. Enter a character;" << endl
        << "    2. Manually put the OS into a sleep or hibernate state;" << endl
        << "    3. Resume the OS from that state;" << endl
```

Does it work with this PR?

**Comment by m4sterchain** [comment]
Hi @z1queue , thank you for submitting the issue and the PR.  To handle the SGX_ERROR_ENCLAVE_LOST error in a more comprehensive way, we need to consider the following,

- For the trusted part
    - Determine which enclave data structure need to be restore after a power transition. We should seal these data before the power transition event occurred. All other in memory data would be lost.

- For the untrusted part
    - The app/tee_binder need to know where the sealed data is before the power transition event. 
    - The app/teed_binder should be responsible to re-init the enclave and restore the sealed data when seeing the SGX_ERROR_ENCLAVE_LOST error.

**Comment by mssun** [comment]
Hi @z1queue, any update on this PR?

**Comment by mssun** [comment]
This PR looks stale. Also, since we are working on refactoring on the `develop` branch. I'll close this PR and leave the issue. Hopefully, we will solve it in the `develop` branch. Thanks for your PR anyway.

**Pull request closed without merging**
