### PR TITLE
Upgrade to SGX SDK v1.1.0

### PR DESCRIPTION
**Pull request by dingelish**
## Description

This PR is to upgrade teaclave-sgx-sdk v1.1.0 and Intel SGX SDK 2.7.1. Everything is fixed and test passed on my workstation.

Fixes # (issue)

## Type of change (select applied and DELETE the others)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API change with a documentation update
- [ ] Additional test coverage
- [x] Code cleanup or just sync with upstream third-party crates

## How Has This Been Tested?

`make sgx-test` passed. CI will soon pass at https://ci.mesalock-linux.org/dingelish/incubator-mesatee/36

## Checklist (check ALL before submitting PR, even not applicable)

- [x] Fork the repo and create your branch from `master`.
- [x] If you've added code that should be tested, add tests.
- [x] If you've changed APIs, update the documentation.
- [x] Ensure the tests pass (see CI results).
- [x] Make sure your code lints/format.

### CODE REVIEW

**Comment by dingelish** [comment]
CI passed
https://ci.mesalock-linux.org/dingelish/incubator-mesatee/36

**Comment by mssun** [comment]
BTW, can you fix this bug in this PR? https://github.com/apache/incubator-teaclave/issues/153

This may cause some issues for submodule updates.

**Comment by dingelish** [comment]
let me try

**Comment by dingelish** [comment]
The fix is to check:
1. if any of the submodule is empty
2. `git submodule summary`'s output is not empty

if either (1) or (2) is satisfied, do submodule update

```diff
diff --git a/cmake/MesaTEEUtils.cmake b/cmake/MesaTEEUtils.cmake
index 8c2f0cd..709937f 100644
--- a/cmake/MesaTEEUtils.cmake
+++ b/cmake/MesaTEEUtils.cmake
@@ -20,7 +20,7 @@ endfunction()

 function(init_submodules)
     execute_process (
-    COMMAND bash -c "if git submodule status | egrep -q '^[-]|^[+]'; then echo 'INFO: Need to reinitialize git submodules' && git submodule update --init --recursive; fi"
+    COMMAND bash -c "if [[ ! $(git submodule foreach ls -A) ]] || [[ $(git submodule summary) ]]; then echo INFO: Need to reinitialize git submodules && git submodule update --init --recursive; fi"
     )
 endfunction()
```
```

**Comment by dingelish** [comment]
New CI result is at https://ci.mesalock-linux.org/dingelish/incubator-mesatee/39

**Pull request merged**
