### PR TITLE
[docker] start Teaclave docker services with auto-detection mechanism

### LINKED ISSUE #553: Support containerized Intel Aesmd service
### Motivation & problem statement
As recommended in [Intel Linux SGX repo.](https://github.com/intel/linux-sgx), the aesmd service is to be built and run as a [containerized service](https://github.com/intel/linux-sgx/blob/master/docker/build/build_and_run_aesm_docker.sh#L41). it created a [named volume](https://github.com/intel/linux-sgx/blob/8abc6dd8cb44e3cef8294c508e77803ffeb8ed12/docker/build/build_and_run_aesm_docker.sh#L36) `aesmd-socket` that should be mounted into `/var/run/aesmd` folder in relying container. 

However, the docker compose files in Teaclave are using the following stanza to mount host based aesmd socket
stanze_aemd_mount
That causes the following failure when starting with any docker compose files.
aesmd_socket_notfound

### Proposed solution
I propose a solution to address this problems to streamline the usage of Teaclave services coordinated with containerized aesmd service through docker compose. the solution requires to introduce the following changes to Teaclave docker compose files and associated documents.

- Remove the following configuration from all docker compose files for all services (3 files)
```
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
```
1. docker-compose-ubuntu-1804-intel-sgx.yml
2. docker-compose-ubuntu-1804-isgx.yml
3. docker-compose-ubuntu-1804.yml 

- Add the following override compose files for host based aesmd socket bind mount for every services
1. docker-compose-ubuntu-1804-intel-sgx-with-host-aesmd-socket.yml
2. docker-compose-ubuntu-1804-isgx-with-host-aesmd-socket.yml
3. docker-compose-ubuntu-1804-with-host-aesmd-socket.yml 

with the following bind mount configuration
```
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
```
- Add the following override compose files for containerized aesmd socket volume mount for every services
1. docker-compose-ubuntu-1804-intel-sgx-with-aesmd-socket-volume.yml
2. docker-compose-ubuntu-1804-isgx-with-aesmd-socket-volume.yml
3. docker-compose-ubuntu-1804-with-aesmd-socket-volume.yml 

with the following volume mount configuration
```
      -  aesmd-socket:/var/run/aesmd
```

In addition, the README.md should be updated accordingly. Thanks.

NOTE: The new feature request to change the existing docker-compose commands that may break user scripts if relying on those commands.

### PR DESCRIPTION
**Pull request by bigdata-memory**
## Description
Added a bash script to detect sgx device and aesm service
heuristically, and start teaclave services without needing to specify
corresponding docker compose file manually. this script can detect and
handle containerized aesm service as well.

Fixes #553 #556 

## Type of change (select or add applied and delete the others)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] API change with a documentation update
- [ ] Additional test coverage
- [ ] Code cleanup or just sync with upstream third-party crates

## Checklist

- [X] Fork the repo and create your branch from `master`.
- [ ] If you've added code that should be tested, add tests.
- [X] If you've changed APIs, update the documentation.
- [ ] Ensure the tests pass (see CI results).
- [ ] Make sure your code lints/format.

### CODE REVIEW

**Comment by mssun** [comment]
Thanks. This is really cool!

Let me test it on servers with different kinds of SGX drivers. (This also bother me since we cannot test this in our CI)

**Comment by bigdata-memory** [comment]
My colleague helped me to identified an issue on his icelake server, I will add a fixup on top of this PR, thanks.

**Comment by mssun** [comment]
I see several docs also contain instructions to use `docker-compose` to start services. Can you also change these? Thanks.

- `docs/my-first-function.md`
- `docs/azure-confidential-computing.md`

**Comment by bigdata-memory** [comment]
> I see several docs also contain instructions to use `docker-compose` to start services. Can you also change these? Thanks.
> 
> * `docs/my-first-function.md`
> * `docs/azure-confidential-computing.md`

sure, will do. thanks.

**Comment by bigdata-memory** [comment]
The CI identified the following issue.
image
Is it related to this PR? anything I should fix in this PR? thanks.

**Comment by mssun** [comment]
> The CI identified the following issue. image Is it related to this PR? or anything I should fix in this PR? thanks.

This is caused by the CI environment. We didn't pin openssl to a specific version. We can resolve this issue in another PR.

**Comment by mssun** [comment]
I have fixed in PR #561. Please help to review and approve this PR (we won't merge any PR without review). Thanks.

**Pull request merged**
