### PR TITLE
Doc: C code can also be compiled using Zig

### PR DESCRIPTION
**Pull request by jedisct1**
## Description

No need for another full LLVM installation if Zig is already installed.

Fixes # (issue)

## Type of change (select or add applied and delete the others)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] API change with a documentation update
- [ ] Additional test coverage
- [ ] Code cleanup or just sync with upstream third-party crates

## How has this been tested?

By compiling the example code using `zig` instead of installing `wasi-sdk`.

## Checklist

- [X] Fork the repo and create your branch from `master`.
- [ ] If you've added code that should be tested, add tests.
- [ ] If you've changed APIs, update the documentation.
- [ ] Ensure the tests pass (see CI results).
- [ ] Make sure your code lints/format.

### CODE REVIEW

**Comment by mssun** [comment]
Let me try if it works in the WAMR executor. Thanks!

**Comment by ya0guang** [comment]
I tried `zig` 0.8 on Ubuntu and it works for `simple_add` example.

I'm not so familiar with `zig`, @jedisct1 could you please explain the benefits of compiling C to WASM with `zig`? It would be great if you can add one or two sentences in the document!

**Comment by mssun** [comment]
> I tried `zig` 0.8 on Ubuntu and it works for `simple_add` example.
> 
> I'm not so familiar with `zig`, @jedisct1 could you please explain the benefits of compiling C to WASM with `zig`? It would be great if you can add one or two sentences in the document!

I believe on benefit he mentioned in the PR is "No need for another full LLVM installation if Zig is already installed."

**Comment by jvz** [comment]
Zig supports all of C along with its own Zig programming language. It's a drop in compiler replacement with friendly errors.

**Review by ya0guang — APPROVED** [review]
Thanks for your explaination and contribution!

**Pull request merged**
